#!/bin/bash
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Purpose:  This script will allow you to save your Docker containers locally

. /usr/sbin/so-elastic-common

IMAGES=$(docker images | grep -E "$DOCKERHUB|registry" | awk '{ print $1 }')
REMOVE_EXISTING_IMAGES=0

#########################################
# Options
#########################################
usage()
{
cat <<EOF
Security Onion Docker Pull
  Options:
  -h         This message
  -r         Remove existing images

EOF
}

while getopts "h:yr" OPTION
do
        case $OPTION in
                h)
                        usage
                        exit 0
                        ;;
                r)
                        REMOVE_EXISTING_IMAGES=1
                        ;;
                *)
                        usage
                        exit 0
                        ;;
        esac
done

if [ $REMOVE_EXISTING_IMAGES -eq 1 ]; then
    # Remove existing images
    for image in $IMAGES; do
        docker rmi $image
    done

    # Pull registry container
    docker pull registry:2
fi

# Pull new images
#for image in $IMAGES; do
#    docker pull $image
#done
